FROM mongo:6

# Install sudo
RUN apt-get update && apt-get install -y sudo

# Allow the mongodb user to execute certain commands as root without a password
RUN echo "mongodb ALL=(root) NOPASSWD: /usr/bin/mkdir, /bin/chown" > /etc/sudoers.d/mongodb

# Add init scripts
COPY --chown=mongodb:mongodb init-ssl.sh /usr/local/bin/init-ssl.sh
COPY --chown=mongodb:mongodb wrapper.sh /usr/local/bin/wrapper.sh
COPY --chown=mongodb:mongodb mongod.conf /etc/mongo/mongod.conf

# Set permissions
RUN chmod +x /usr/local/bin/init-ssl.sh
RUN chmod +x /usr/local/bin/wrapper.sh

ENTRYPOINT ["wrapper.sh"]
CMD [ "mongod", "--config=/etc/mongo/mongod.conf", "--ipv6", "--bind_ip=::,0.0.0.0" ]
